suppressPackageStartupMessages({library(Seurat); library(Matrix); library(digest)})
source("analysis_development_v2/scripts/config.R")
s <- readRDS(datapath("BLA_E18_P0_P10_P21_seurat_v2.rds"))
stopifnot(inherits(s, "Seurat"))
before <- digest(LayerData(s, layer = "counts"), algo = "xxhash64")
slim <- DietSeurat(s, layers = c("counts", "data"), dimreducs = names(s@reductions), graphs = names(s@graphs), misc = TRUE)
stopifnot(identical(before, digest(LayerData(slim, layer = "counts"), algo = "xxhash64")), identical(slim[[]], s[[]]))
export <- file.path(ROOT, "release", "private_data"); dir.create(export, recursive = TRUE, showWarnings = FALSE)
out <- file.path(export, "BLA_E18_P0_P10_P21_seurat_v2.uncompressed.rds")
saveRDS(slim, out, compress = FALSE)
test <- readRDS(out)
stopifnot(inherits(test, "Seurat"), identical(test[[]], slim[[]]),
  identical(before, digest(LayerData(test, layer = "counts"), algo = "xxhash64")), identical(dim(test), dim(s)))
save_table(data.frame(check = c("export_counts_identical", "export_metadata_identical", "export_roundtrip_valid"), passed = TRUE), "data_export_validation.csv")
write.csv(cbind(cell_id = colnames(slim), slim[[]]), file.path(export, "cell_metadata.csv"), row.names = FALSE)
file.copy(tabpath("all_input_barcodes_qc.csv"), file.path(export, "all_input_barcodes_qc.csv"), overwrite = TRUE)
file.copy(tabpath("doublet_calls.csv"), file.path(export, "doublet_calls.csv"), overwrite = TRUE)
file.copy(datapath("01_qc_input.rds"), file.path(export, "all_QC_common_counts_input.rds"), overwrite = TRUE)
file.copy(datapath("sample_population_pseudobulk.rds"), file.path(export, "sample_population_pseudobulk.rds"), overwrite = TRUE)
file.copy(NEW_INPUT, file.path(export, "hansol2_combined_seurat.rds"), overwrite = TRUE)
writeLines(capture.output(sessionInfo()), file.path(ROOT, "logs", "sessionInfo_export.txt"))
logmsg("Data prepared locally, not automatically uploaded:", export)
